version: 0.2

phases:
  pre_build:
    commands:
      - echo Log in DockerHub...
      - docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $DOCKERHUB_LOGIN/$IMAGE_REPO_NAME:$IMAGE_TAG .   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $DOCKERHUB_LOGIN/$IMAGE_REPO_NAME:$IMAGE_TAG
